### ISSUE TITLE
[HELP] Possible to update the priority of sources without registering the sources?

### ISSUE THREAD

**Issue by megalithic** [ncm2/ncm2#49]
@roxma

This is more of a request for information, as I didn't see it in the help doc.

I'm wanting to explicitly set just priority order of sources, and maybe even just their mark. So, for instance, I'd like to be able to just set UltiSnips source higher than LSP source, so that [us] is always above [lsp] in the autocomplete menu list.

Is there a way to do this without registering a new source?

Thanks so much for bringing this library back to life and better than before!

**Comment by roxma** [comment]
Say, you want to customize ncm2-bufword, You could read how the source is initialized here :  https://github.com/ncm2/ncm2-bufword/blob/master/autoload/ncm2_bufword.vim#L11

To change the options, in your vimrc, before the source is loaded, use  `let g:ncm2_bufword#source = {'priority': 6}`.

The ultisnips source is similar: https://github.com/ncm2/ncm2-ultisnips/blob/master/autoload/ncm2_ultisnips.vim#L70

 `let g:ncm2_ultisnips#source = {'priority': 10}`

NOTE that I have just pushed an update to ncm2-ultisnips, you need to update the plugin before apply your config.

**Comment by roxma** [comment]
To change the source registered by LanguageClient-neovim, you could use `autocmd User Ncm2RegisterSource`  (enabled by https://github.com/ncm2/ncm2/commit/63bf319a77148072190411bccafbfc1f8cfdc8d0), then check and modify the ncm2 sources registry `ncm2#_s('sources')`.

**Comment by balta2ar** [comment]
It's a bit inconvenient that it's not enforced on ncm2 side, because it means that sources must be written in a way that supports overrides. And now many sources need to be updated to get rid of "source_overrides" in favor of simpler extend + keep (for example, https://github.com/filipekiss/ncm2-look.vim/blob/master/autoload/ncm2_look.vim#L10)

**Comment by roxma** [comment]
@balta2ar 

You could use `ncm2#_s('sources')` to access all registered sources on ncm2 side.

**Comment by roxma** [comment]
`ncm2#override_source` is added.

```
    call ncm2#override_source('bufword', {s->extend(s, {'priority': 3})})

    or

    call ncm2#override_source('bufword', {'priority': 3})
```

**Comment by filipekiss** [comment]
Hey @balta2ar, can you please explain to me why [look.vim] doesn't use the extend + keep as you mentioned? The only caveat is you need to set the configs before loading the source, but it does respect any config set before initializing it. Care to explain how I could do better with it? :) Thanks!

[look.vim]: https://github.com/filipekiss/ncm2-look.vim

**Comment by balta2ar** [comment]
@filipekiss Hi! Sorry, I didn't mean to throw stones to look.vim in particular. In fact, it does correct config loading, it uses `extend` and "source_override".

But my point was that the user should not depend on whether option override is carefully implemented on the plugin side or not (because there could be a source that plainly ignores overrides), and that ncm2 core should allow user to override any option of any source, which roxma already did in the commit above.

**Comment by filipekiss** [comment]
@balta2ar Ah, I see. No problem, I actually didn't take the comment as bashing or anything like that. I just thought I might have made something wrong and was failing to see where the problem was. Thank you for you consideration! (And if you ever feel like something should be changed on look.vim, open an issue or make a pull-request!)
